// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	UserName string      `json:"userName"`
	Password string      `json:"password"`
	Data     interface{} `json:"data,omitempty,optional"`
}

type UserLoginResp struct {
	UserId      int64  `json:"userId"`
	Nickname    string `json:"nickname"`
	AccessToken string `json:"accessToken"`
}

type UserInfoReq struct {
	UserId   int64  `json:"userId"`
	UserName string `json:"userName,optional"`
}

type UserInfoResp struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}
